apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: simple-source-transform
spec:
  vertices:
    - name: in
      source:
        # A self data generating source
        generator:
          rpu: 300
          duration: 1s
          keyCount: 5
          value: 5
        transformer:
          container:
            image: quay.io/numaio/numaflow-js/simple-source-transform:stable
            imagePullPolicy: IfNotPresent
    - name: reduce
      partitions: 1
      udf:
        container:
          image: quay.io/numaio/numaflow-js/reduce:stable
          imagePullPolicy: Never
        groupBy:
          window:
            fixed:
              length: 10s
          keyed: false
          storage:
            emptyDir: { }
    - name: out
      sink:
        udsink:
          container:
            image: quay.io/numaio/numaflow-js/log-sink:stable
            imagePullPolicy: IfNotPresent
  edges:
    - from: in
      to: cat
    - from: cat
      to: out
